name: Code Style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pint:
    name: Check code style (Pint)
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, xml, curl, bcmath
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run Pint
        run: ./vendor/bin/pint --test
