name: Laravel Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    # Temporary MySQL database
    services:
      mysql:
        image: mysql:8.4

        env:
          MYSQL_DATABASE: threadforge_testing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    # Laravel test environment
    env:
      APP_ENV: testing
      APP_DEBUG: true

      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: threadforge_testing
      DB_USERNAME: laravel
      DB_PASSWORD: secret

      CACHE_STORE: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      MAIL_MAILER: array

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, xml, curl, bcmath, pdo_mysql
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
